package servicenow

import (
	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

const CmdbCITableName = "cmdb_ci"

//// TABLE DEFINITION

func tableServicenowCmdbCi() *plugin.Table {
	return &plugin.Table{
		Name:             "servicenow_cmdb_ci",
		DefaultTransform: transform.FromCamel(),
		Description:      "Represents configuration items and their attributes in the CMDB.",
		List: &plugin.ListConfig{
			KeyColumns: plugin.OptionalColumns([]string{"asset_tag", "attestation_status", "attributes", "category", "comments", "correlation_id", "cost_cc", "discovery_source", "dns_domain", "due_in", "environment", "fqdn", "gl_account", "invoice_number", "ip_address", "justification", "lease_id", "mac_address", "model_number", "name", "po_number", "purchase_date", "serial_number", "short_description", "subcategory", "sys_class_name", "sys_class_path", "sys_created_by", "sys_domain_path", "sys_id", "sys_updated_by", "warranty_expiration"}),
			Hydrate:    listServicenowObjectsByTable(CmdbCITableName, nil),
		},
		Get: &plugin.GetConfig{
			Hydrate:    getServicenowObjectbyID(CmdbCITableName),
			KeyColumns: plugin.SingleColumn("sys_id"),
		},
		Columns: commonColumns([]*plugin.Column{
			{Name: "asset_tag", Description: "Unique identifier for the asset.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "asset_tag")},
			{Name: "asset", Description: "The asset associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "asset")},
			{Name: "assigned_to", Description: "Person or group assigned to the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "assigned_to")},
			{Name: "assigned", Description: "Flag indicating if the configuration item is assigned.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "assigned").Transform(parseDateTime)},
			{Name: "assignment_group", Description: "Group assigned to the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "assignment_group")},
			{Name: "attestation_score", Description: "Score representing the attestation status of the configuration item.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "attestation_score")},
			{Name: "attestation_status", Description: "Status of attestation for the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "attestation_status")},
			{Name: "attested_by", Description: "Person who attested the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "attested_by")},
			{Name: "attested_date", Description: "Date when the configuration item was attested.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "attested_date").Transform(parseDateTime)},
			{Name: "attested", Description: "Flag indicating if the configuration item is attested.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "attested")},
			{Name: "attributes", Description: "Additional attributes associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "attributes")},
			{Name: "business_unit", Description: "Business unit associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "business_unit")},
			{Name: "can_print", Description: "Flag indicating if the configuration item can be printed.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "can_print")},
			{Name: "category", Description: "Category of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "category")},
			{Name: "change_control", Description: "Change control information for the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "change_control")},
			{Name: "checked_in", Description: "Flag indicating if the configuration item is checked in.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "checked_in").Transform(parseDateTime)},
			{Name: "checked_out", Description: "Flag indicating if the configuration item is checked out.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "checked_out").Transform(parseDateTime)},
			{Name: "comments", Description: "Comments or notes related to the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "comments")},
			{Name: "company", Description: "Company associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "company")},
			{Name: "correlation_id", Description: "ID used to correlate related configuration items.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "correlation_id")},
			{Name: "cost_cc", Description: "Cost center associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "cost_cc")},
			{Name: "cost_center", Description: "Cost center associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "cost_center")},
			{Name: "cost", Description: "Cost of the configuration item.", Type: proto.ColumnType_DOUBLE, Transform: transform.FromP(getFieldFromSObjectMap, "cost")},
			{Name: "delivery_date", Description: "Date of delivery for the configuration item.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "delivery_date").Transform(parseDateTime)},
			{Name: "department", Description: "Department associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "department")},
			{Name: "discovery_source", Description: "Source of discovery for the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "discovery_source")},
			{Name: "dns_domain", Description: "DNS domain associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "dns_domain")},
			{Name: "due_in", Description: "Time remaining for the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "due_in")},
			{Name: "due", Description: "Due date for the configuration item.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "due").Transform(parseDateTime)},
			{Name: "duplicate_of", Description: "Which CI is this a duplicate of.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "duplicate_of")},
			{Name: "environment", Description: "Environment associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "environment")},
			{Name: "fault_count", Description: "Number of faults associated with the configuration item.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "fault_count")},
			{Name: "first_discovered", Description: "Date when the configuration item was first discovered.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "first_discovered").Transform(parseDateTime)},
			{Name: "fqdn", Description: "Fully Qualified Domain Name (FQDN) of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "fqdn")},
			{Name: "gl_account", Description: "General ledger account associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "gl_account")},
			{Name: "install_date", Description: "Date when the configuration item was installed.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "install_date").Transform(parseDateTime)},
			{Name: "install_status", Description: "Installation status of the configuration item.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "install_status")},
			{Name: "invoice_number", Description: "Invoice number associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "invoice_number")},
			{Name: "ip_address", Description: "IP address of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "ip_address")},
			{Name: "justification", Description: "Justification for the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "justification")},
			{Name: "last_discovered", Description: "Most recent discovery.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "last_discovered").Transform(parseDateTime)},
			{Name: "lease_id", Description: "ID of the lease associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "lease_id")},
			{Name: "life_cycle_stage_status", Description: "The specific status of a CI within its life cycle phase.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "life_cycle_stage_status")},
			{Name: "life_cycle_stage", Description: "Life cycle stage of the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "life_cycle_stage")},
			{Name: "location", Description: "Location of the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "location")},
			{Name: "mac_address", Description: "MAC address of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "mac_address")},
			{Name: "maintenance_schedule", Description: "Maintenance schedule associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "maintenance_schedule")},
			{Name: "managed_by_group", Description: "Group responsible for managing the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "managed_by_group")},
			{Name: "managed_by", Description: "Person responsible for managing the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "managed_by")},
			{Name: "manufacturer", Description: "Manufacturer of the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "manufacturer")},
			{Name: "model_id", Description: "ID of the model associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "model_id")},
			{Name: "model_number", Description: "Model number of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "model_number")},
			{Name: "monitor", Description: "Flag indicating if the configuration item is monitored.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "monitor")},
			{Name: "name", Description: "Name of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "name")},
			{Name: "operational_status", Description: "Operational status of the configuration item.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "operational_status")},
			{Name: "order_date", Description: "Date when the configuration item was ordered.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "order_date").Transform(parseDateTime)},
			{Name: "owned_by", Description: "Person or group that owns the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "owned_by")},
			{Name: "po_number", Description: "Purchase order number associated with the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "po_number")},
			{Name: "purchase_date", Description: "Date when the configuration item was purchased.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "purchase_date")},
			{Name: "schedule", Description: "Schedule associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "schedule")},
			{Name: "serial_number", Description: "Serial number of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "serial_number")},
			{Name: "short_description", Description: "Short description of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "short_description")},
			{Name: "skip_sync", Description: "Flag indicating if synchronization should be skipped for the configuration item.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "skip_sync")},
			{Name: "start_date", Description: "Start date associated with the configuration item.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "start_date").Transform(parseDateTime)},
			{Name: "subcategory", Description: "Subcategory of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "subcategory")},
			{Name: "support_group", Description: "Support group responsible for the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "support_group")},
			{Name: "supported_by", Description: "Person or group responsible for supporting the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "supported_by")},
			{Name: "sys_class_name", Description: "Name of the configuration item's class.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_class_name")},
			{Name: "sys_class_path", Description: "Path of the configuration item's class.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_class_path")},
			{Name: "sys_created_by", Description: "User who created the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_created_by")},
			{Name: "sys_created_on", Description: "Date and time when the configuration item was created.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "sys_created_on").Transform(parseDateTime)},
			{Name: "sys_domain_path", Description: "Path of the configuration item's domain.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_domain_path")},
			{Name: "sys_domain", Description: "Domain associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "sys_domain")},
			{Name: "sys_id", Description: "Unique identifier (Sys ID) of the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_id")},
			{Name: "sys_mod_count", Description: "Number of times the configuration item has been modified.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "sys_mod_count")},
			{Name: "sys_updated_by", Description: "User who last updated the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_updated_by")},
			{Name: "sys_updated_on", Description: "Date and time when the configuration item was last updated.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "sys_updated_on").Transform(parseDateTime)},
			{Name: "unverified", Description: "Flag indicating if the configuration item is unverified.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "unverified")},
			{Name: "vendor", Description: "Vendor associated with the configuration item.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "vendor")},
			{Name: "warranty_expiration", Description: "Expiration date of the warranty for the configuration item.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "warranty_expiration")},
		}),
	}
}
