package servicenow

import (
	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

const CmdbCIServerTableName = "cmdb_ci_server"

//// TABLE DEFINITION

func tableServicenowCmdbCiServer() *plugin.Table {
	return &plugin.Table{
		Name:             "servicenow_cmdb_ci_server",
		DefaultTransform: transform.FromCamel(),
		Description:      "Configuration Item Server.",
		List: &plugin.ListConfig{
			Hydrate: listServicenowObjectsByTable(CmdbCIServerTableName, nil),
		},
		Get: &plugin.GetConfig{
			Hydrate:    getServicenowObjectbyID(CmdbCIServerTableName),
			KeyColumns: plugin.SingleColumn("sys_id"),
		},
		Columns: []*plugin.Column{
			{Name: "asset_tag", Description: "Asset tag.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "asset_tag")},
			{Name: "asset", Description: "Asset.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "asset")},
			{Name: "assigned_to", Description: "Assigned to.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "assigned_to")},
			{Name: "assigned", Description: "Assigned.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "assigned").Transform(parseDateTime)},
			{Name: "assignment_group", Description: "Change Group.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "assignment_group")},
			{Name: "attestation_score", Description: "Attestation Score.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "attestation_score")},
			{Name: "attestation_status", Description: "Attestation Status.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "attestation_status")},
			{Name: "attested_by", Description: "Attested By.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "attested_by")},
			{Name: "attested_date", Description: "Attested Date.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "attested_date").Transform(parseDateTime)},
			{Name: "attested", Description: "Attested.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "attested")},
			{Name: "attributes", Description: "Attributes.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "attributes")},
			{Name: "business_unit", Description: "Business Unit.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "business_unit")},
			{Name: "can_print", Description: "Can Print.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "can_print")},
			{Name: "category", Description: "Category.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "category")},
			{Name: "cd_rom", Description: "CD.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "cd_rom")},
			{Name: "cd_speed", Description: "CD Speed.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "cd_speed")},
			{Name: "change_control", Description: "Approval group.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "change_control")},
			{Name: "chassis_type", Description: "Chassis type.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "chassis_type")},
			{Name: "checked_in", Description: "Checked in.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "checked_in").Transform(parseDateTime)},
			{Name: "checked_out", Description: "Checked out.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "checked_out").Transform(parseDateTime)},
			{Name: "classification", Description: "Classification.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "classification")},
			{Name: "comments", Description: "Comments.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "comments")},
			{Name: "company", Description: "Company.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "company")},
			{Name: "correlation_id", Description: "Correlation ID.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "correlation_id")},
			{Name: "cost_cc", Description: "Cost currency.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "cost_cc")},
			{Name: "cost_center", Description: "Cost center.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "cost_center")},
			{Name: "cost", Description: "Cost.", Type: proto.ColumnType_DOUBLE, Transform: transform.FromP(getFieldFromSObjectMap, "cost")},
			{Name: "cpu_core_count", Description: "CPU core count.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "cpu_core_count")},
			{Name: "cpu_core_thread", Description: "CPU core thread.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "cpu_core_thread")},
			{Name: "cpu_count", Description: "CPU count.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "cpu_count")},
			{Name: "cpu_manufacturer", Description: "CPU manufacturer.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "cpu_manufacturer")},
			{Name: "cpu_name", Description: "CPU name.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "cpu_name")},
			{Name: "cpu_speed", Description: "CPU speed (MHz). ", Type: proto.ColumnType_DOUBLE, Transform: transform.FromP(getFieldFromSObjectMap, "cpu_speed")},
			{Name: "cpu_type", Description: "CPU type.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "cpu_type")},
			{Name: "default_gateway", Description: "Default Gateway.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "default_gateway")},
			{Name: "delivery_date", Description: "Order received.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "delivery_date").Transform(parseDateTime)},
			{Name: "department", Description: "Department.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "department")},
			{Name: "discovery_source", Description: "Discovery source.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "discovery_source")},
			{Name: "disk_space", Description: "Disk space (GB). ", Type: proto.ColumnType_DOUBLE, Transform: transform.FromP(getFieldFromSObjectMap, "disk_space")},
			{Name: "dns_domain", Description: "DNS Domain.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "dns_domain")},
			{Name: "dr_backup", Description: "Disaster backup.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "dr_backup")},
			{Name: "due_in", Description: "Due in.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "due_in")},
			{Name: "due", Description: "Due.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "due").Transform(parseDateTime)},
			{Name: "duplicate_of", Description: "Duplicate Of.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "duplicate_of")},
			{Name: "environment", Description: "Environment.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "environment")},
			{Name: "fault_count", Description: "Fault count.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "fault_count")},
			{Name: "firewall_status", Description: "Firewall status.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "firewall_status")},
			{Name: "first_discovered", Description: "First discovered.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "first_discovered").Transform(parseDateTime)},
			{Name: "floppy", Description: "Floppy.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "floppy")},
			{Name: "form_factor", Description: "Form factor.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "form_factor")},
			{Name: "fqdn", Description: "Fully qualified domain name.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "fqdn")},
			{Name: "gl_account", Description: "GL account.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "gl_account")},
			{Name: "hardware_status", Description: "Hardware Status.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "hardware_status")},
			{Name: "hardware_substatus", Description: "Substatus.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "hardware_substatus")},
			{Name: "host_name", Description: "Host name.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "host_name")},
			{Name: "install_date", Description: "Installed.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "install_date").Transform(parseDateTime)},
			{Name: "install_status", Description: "Install Status.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "install_status")},
			{Name: "internet_facing", Description: "Internet Facing.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "internet_facing")},
			{Name: "invoice_number", Description: "Invoice number.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "invoice_number")},
			{Name: "ip_address", Description: "IP Address.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "ip_address")},
			{Name: "justification", Description: "Justification.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "justification")},
			{Name: "last_discovered", Description: "Most recent discovery.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "last_discovered").Transform(parseDateTime)},
			{Name: "lease_id", Description: "Lease contract.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "lease_id")},
			{Name: "life_cycle_stage_status", Description: "Life Cycle Stage Status.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "life_cycle_stage_status")},
			{Name: "life_cycle_stage", Description: "Life Cycle Stage.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "life_cycle_stage")},
			{Name: "location", Description: "Location.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "location")},
			{Name: "mac_address", Description: ". ", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "mac_address")},
			{Name: "maintenance_schedule", Description: "Maintenance schedule.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "maintenance_schedule")},
			{Name: "managed_by_group", Description: "Managed By Group.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "managed_by_group")},
			{Name: "managed_by", Description: "Managed by.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "managed_by")},
			{Name: "manufacturer", Description: "Manufacturer.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "manufacturer")},
			{Name: "model_id", Description: "Model ID.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "model_id")},
			{Name: "model_number", Description: "Model number.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "model_number")},
			{Name: "monitor", Description: "Monitor.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "monitor")},
			{Name: "most_frequent_user", Description: "Most frequent logged in user.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "most_frequent_user")},
			{Name: "name", Description: "Name.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "name")},
			{Name: "object_id", Description: "Object ID.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "object_id")},
			{Name: "operational_status", Description: "Operational status.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "operational_status")},
			{Name: "order_date", Description: "Ordered.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "order_date").Transform(parseDateTime)},
			{Name: "os_address_width", Description: "OS Address Width (bits). ", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "os_address_width")},
			{Name: "os_domain", Description: "OS Domain.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "os_domain")},
			{Name: "os_service_pack", Description: "OS Service Pack.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "os_service_pack")},
			{Name: "os_version", Description: "OS Version.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "os_version")},
			{Name: "os", Description: "Operating System.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "os")},
			{Name: "owned_by", Description: "Owned by.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "owned_by")},
			{Name: "po_number", Description: "PO number.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "po_number")},
			{Name: "purchase_date", Description: "Purchased.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "purchase_date")},
			{Name: "ram", Description: "RAM (MB). ", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "ram")},
			{Name: "schedule", Description: "Schedule.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "schedule")},
			{Name: "serial_number", Description: "Serial number.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "serial_number")},
			{Name: "short_description", Description: "Description.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "short_description")},
			{Name: "skip_sync", Description: "Skip sync.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "skip_sync")},
			{Name: "start_date", Description: "Start date.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "start_date").Transform(parseDateTime)},
			{Name: "subcategory", Description: "Subcategory.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "subcategory")},
			{Name: "support_group", Description: "Support group.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "support_group")},
			{Name: "supported_by", Description: "Supported by.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "supported_by")},
			{Name: "sys_class_name", Description: "Class.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_class_name")},
			{Name: "sys_class_path", Description: "Sys class path.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_class_path")},
			{Name: "sys_created_by", Description: "Created by.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_created_by")},
			{Name: "sys_created_on", Description: "Created.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "sys_created_on").Transform(parseDateTime)},
			{Name: "sys_domain_path", Description: "Domain Path.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_domain_path")},
			{Name: "sys_domain", Description: "Domain.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "sys_domain")},
			{Name: "sys_id", Description: "Sys ID.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_id")},
			{Name: "sys_mod_count", Description: "Updates.", Type: proto.ColumnType_INT, Transform: transform.FromP(getFieldFromSObjectMap, "sys_mod_count")},
			{Name: "sys_updated_by", Description: "Updated by.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "sys_updated_by")},
			{Name: "sys_updated_on", Description: "Updated.", Type: proto.ColumnType_TIMESTAMP, Transform: transform.FromP(getFieldFromSObjectMap, "sys_updated_on").Transform(parseDateTime)},
			{Name: "unverified", Description: "Requires verification.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "unverified")},
			{Name: "used_for", Description: "Used for.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "used_for")},
			{Name: "vendor", Description: "Vendor.", Type: proto.ColumnType_JSON, Transform: transform.FromP(getFieldFromSObjectMap, "vendor")},
			{Name: "virtual", Description: "Is Virtual.", Type: proto.ColumnType_BOOL, Transform: transform.FromP(getFieldFromSObjectMap, "virtual")},
			{Name: "warranty_expiration", Description: "Warranty expiration.", Type: proto.ColumnType_STRING, Transform: transform.FromP(getFieldFromSObjectMap, "warranty_expiration")},
		},
	}
}
